name: dataset-processor
channels:
  - pytorch
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python>=3.10
  - pytorch>=2.4.0
  - pytorch-cuda>=12.4
  - torchvision>=0.8
  - torchaudio
  - tqdm
  - pandas
  - matplotlib
  - pip
  - pycocotools>=2
  - pip:
    - opencv-python
    - scipy
    - psutil
    - piexif
    - xlsxwriter
    - openai
    - anthropic
    - git+https://github.com/cribbinsb/stuff.git
    - git+https://github.com/cribbinsb/ultralytics.git@multilabel
